package utils

// SuffixOf Helper function, returns the possible suffix of the Content-Type given
func SuffixOf(contentType string) string {
	switch contentType {
	case "application/x-001":
		return ".001"
	case "text/h323":
		return ".323"
	case "drawing/907":
		return ".907"
	case "audio/x-mei-aac":
		return "acp"
	case "audio/aiff":
		return "aiff"
	case "text/asa":
		return "asa"
	case "text/asp":
		return "asp"
	case "audio/basic":
		return "au"
	case "application/vnd.adobe.workflow":
		return "awf"
	case "application/x-bmp":
		return "bmp"
	case "application/x-c4t":
		return "c4t"
	case "application/x-cals":
		return "cal"
	case "application/x-netcdf":
		return "cdf"
	case "application/x-cel":
		return "cel"
	case "application/x-cit":
		return "cit"
	case "application/x-cmx":
		return "cmx"
	case "application/pkix-crl":
		return "crl"
	case "application/x-csi":
		return "csi"
	case "application/x-cut":
		return "cut"
	case "application/x-dbm":
		return "dbm"
	case "application/x-dib":
		return "dib"
	case "application/msword":
		return "doc"
	case "application/x-drw":
		return "drw"
	case "Model/vnd.dwf":
		return "dwf"
	case "application/x-dwg":
		return "dwg"
	case "application/x-dxf":
		return "dxf"
	case "application/x-emf":
		return "emf"
	case "application/x-ps":
		return "eps"
	case "application/x-ebx":
		return "etd"
	case "image/fax":
		return "fax"
	case "application/fractals":
		return "fif"
	case "application/x-frm":
		return "frm"
	case "application/x-gbr":
		return "gbr"
	case "image/gif":
		return "gif"
	case "application/x-gp4":
		return "gp4"
	case "application/x-hmr":
		return "hmr"
	case "application/x-hpl":
		return "hpl"
	case "application/x-hrf":
		return "hrf"
	case "text/x-component":
		return "htc"
	case "text/html":
		return "html"
	case "image/x-icon":
		return "ico"
	case "application/x-iff":
		return "iff"
	case "application/x-igs":
		return "igs"
	case "application/x-img":
		return "img"
	case "application/x-internet-signup":
		return "isp"
	case "java/*":
		return "java"
	case "image/jpeg":
		return "jpeg"
	case "application/x-jpg":
		return "jpg"
	case "application/x-laplayer-reg":
		return "lar"
	case "audio/x-liquid-secure":
		return "lavs"
	case "audio/x-la-lms":
		return "lmsff"
	case "application/x-ltr":
		return "ltr"
	case "application/x-troff-man":
		return "man"
	case "application/msaccess":
		return "mdb"
	case "message/rfc822":
		return "mhtml"
	case "application/x-mil":
		return "mil"
	case "audio/x-musicnet-download":
		return "mnd"
	case "audio/mp1":
		return "mp1"
	case "video/mpeg4":
		return "mp4"
	case "video/mpg":
		return "mpeg"
	case "audio/rn-mpeg":
		return "mpga"
	case "image/pnetvue":
		return "net"
	case "application/x-out":
		return "out"
	case "application/x-pkcs12":
		return "p12"
	case "application/x-pkcs7-certreqresp":
		return "p7r"
	case "application/x-pc5":
		return "pc5"
	case "application/x-pcl":
		return "pcl"
	case "application/vnd.adobe.pdx":
		return "pdx"
	case "application/x-pgl":
		return "pgl"
	case "application/vnd.ms-pki.pko":
		return "pko"
	case "application/x-plt":
		return "plt"
	case "application/x-png":
		return "png"
	case "application/x-ppt":
		return "ppt"
	case "application/pics-rules":
		return "prf"
	case "application/x-prt":
		return "prt"
	case "audio/vnd.rn-realaudio":
		return "ra"
	case "application/x-ras":
		return "ras"
	case "application/x-red":
		return "red"
	case "application/vnd.rn-realsystem-rjs":
		return "rjs"
	case "application/x-rlc":
		return "rlc"
	case "application/vnd.rn-realmedia":
		return "rm"
	case "application/vnd.rn-realmedia-secure":
		return "rms"
	case "application/vnd.rn-realsystem-rmx":
		return "rmx"
	case "image/vnd.rn-realpix":
		return "rp"
	case "application/vnd.rn-rsml":
		return "rsml"
	case "video/vnd.rn-realvideo":
		return "rv"
	case "application/x-sat":
		return "sat"
	case "application/x-sdw":
		return "sdw"
	case "application/x-slb":
		return "slb"
	case "drawing/x-slk":
		return "slk"
	case "application/smil":
		return "smil"
	case "application/futuresplash":
		return "spl"
	case "application/streamingmedia":
		return "ssm"
	case "application/vnd.ms-pki.stl":
		return "stl"
	case "application/x-sty":
		return "sty"
	case "application/x-shockwave-flash":
		return "swf"
	case "application/x-tg4":
		return "tg4"
	case "image/tiff":
		return "tiff"
	case "drawing/x-top":
		return "top"
	case "application/x-icq":
		return "uin"
	case "text/x-vcard":
		return "vcf"
	case "application/x-vpeg005":
		return "vpg"
	case "application/x-vsd":
		return "vsd"
	case "audio/wav":
		return "wav"
	case "application/x-wb1":
		return "wb1"
	case "application/x-wb3":
		return "wb3"
	case "application/x-wk4":
		return "wk4"
	case "application/x-wks":
		return "wks"
	case "audio/x-ms-wma":
		return "wma"
	case "application/x-wmf":
		return "wmf"
	case "video/x-ms-wmv":
		return "wmv"
	case "application/x-ms-wmz":
		return "wmz"
	case "application/x-wpd":
		return "wpd"
	case "application/vnd.ms-wpl":
		return "wpl"
	case "application/x-wr1":
		return "wr1"
	case "application/x-wrk":
		return "wrk"
	case "application/x-ws":
		return "ws2"
	case "application/vnd.adobe.xdp":
		return "xdp"
	case "application/vnd.adobe.xfd":
		return "xfd"
	case "application/x-xls":
		return "xls"
	case "text/xml":
		return "xml"
	case "application/x-xwd":
		return "xwd"
	case "application/x-x_t":
		return "x_t"
	case "application/vnd.android.package-archive":
		return "apk"
	case "application/x-301":
		return "301"
	case "application/x-906":
		return "906"
	case "application/x-a11":
		return "a11"
	case "application/x-anv":
		return "anv"
	case "video/x-ms-asf":
		return "asf"
	case "video/avi":
		return "avi"
	case "application/x-bot":
		return "bot"
	case "application/x-c90":
		return "c90"
	case "application/vnd.ms-pki.seccat":
		return "cat"
	case "application/x-cdr":
		return "cdr"
	case "application/x-cgm":
		return "cgm"
	case "application/x-cmp":
		return "cmp"
	case "application/x-cot":
		return "cot"
	case "application/x-x509-ca-cert":
		return "crt"
	case "text/css":
		return "css"
	case "application/x-dbf":
		return "dbf"
	case "application/x-dbx":
		return "dbx"
	case "application/x-dcx":
		return "dcx"
	case "application/x-dgn":
		return "dgn"
	case "application/x-dwf":
		return "dwf"
	case "application/x-dxb":
		return "dxb"
	case "application/vnd.adobe.edn":
		return "edn"
	case "application/x-epi":
		return "epi"
	case "application/postscript":
		return "eps"
	case "application/x-msdownload":
		return "exe"
	case "application/vnd.fdf":
		return "fdf"
	case "application/x-g4":
		return "g4"
	case "application/x-":
		return ""
	case "application/x-gl2":
		return "gl2"
	case "application/x-hgl":
		return "hgl"
	case "application/x-hpgl":
		return "hpg"
	case "application/mac-binhex40":
		return "hqx"
	case "application/hta":
		return "hta"
	case "text/webviewhtml":
		return "htt"
	case "application/x-icb":
		return "icb"
	case "application/x-ico":
		return "ico"
	case "application/x-iphone":
		return "iii"
	case "video/x-ivf":
		return "IVF"
	case "application/x-jpe":
		return "jpe"
	case "application/x-javascript":
		return "js"
	case "audio/x-liquid-file":
		return "la1"
	case "application/x-latex":
		return "latex"
	case "application/x-lbm":
		return "lbm"
	case "video/x-mpeg":
		return "m1v"
	case "audio/mpegurl":
		return "m3u"
	case "application/x-mac":
		return "mac"
	case "application/x-mdb":
		return "mdb"
	case "application/x-mi":
		return "mi"
	case "audio/mid":
		return "midi"
	case "audio/x-musicnet-stream":
		return "mns"
	case "video/x-sgi-movie":
		return "movie"
	case "audio/mp2":
		return "mp2"
	case "audio/mp3":
		return "mp3"
	case "video/x-mpg":
		return "mpa"
	case "video/mpeg":
		return "mpv2"
	case "application/vnd.ms-project":
		return "mpx"
	case "application/x-mmxp":
		return "mxp"
	case "application/x-nrf":
		return "nrf"
	case "text/x-ms-odc":
		return "odc"
	case "application/pkcs10":
		return "p10"
	case "application/x-pkcs7-certificates":
		return "p7b"
	case "application/pkcs7-mime":
		return "p7m"
	case "application/pkcs7-signature":
		return "p7s"
	case "application/x-pci":
		return "pci"
	case "application/x-pcx":
		return "pcx"
	case "application/pdf":
		return "pdf"
	case "application/x-pic":
		return "pic"
	case "application/x-perl":
		return "pl"
	case "audio/scpls":
		return "pls"
	case "image/png":
		return "png"
	case "application/x-ppm":
		return "ppm"
	case "application/vnd.ms-powerpoint":
		return "ppt"
	case "application/x-pr":
		return "pr"
	case "application/x-prn":
		return "prn"
	case "application/x-ptn":
		return "ptn"
	case "text/vnd.rn-realtext3d":
		return "r3t"
	case "audio/x-pn-realaudio":
		return "ram"
	case "application/rat-file":
		return "rat"
	case "application/vnd.rn-recording":
		return "rec"
	case "application/x-rgb":
		return "rgb"
	case "application/vnd.rn-realsystem-rjt":
		return "rjt"
	case "application/x-rle":
		return "rle"
	case "application/vnd.adobe.rmf":
		return "rmf"
	case "application/vnd.rn-realsystem-rmj":
		return "rmj"
	case "application/vnd.rn-rn_music_package":
		return "rmp"
	case "application/vnd.rn-realmedia-vbr":
		return "rmvb"
	case "application/vnd.rn-realplayer":
		return "rnx"
	case "audio/x-pn-realaudio-plugin":
		return "rpm"
	case "text/vnd.rn-realtext":
		return "rt"
	case "application/x-rtf":
		return "rtf"
	case "application/x-sam":
		return "sam"
	case "application/sdp":
		return "sdp"
	case "application/x-stuffit":
		return "sit"
	case "application/x-sld":
		return "sld"
	case "application/x-smk":
		return "smk"
	case "application/vnd.ms-pki.certstore":
		return "sst"
	case "application/x-tdf":
		return "tdf"
	case "application/x-tga":
		return "tga"
	case "application/x-tif":
		return "tif"
	case "application/x-bittorrent":
		return "torrent"
	case "text/plain":
		return "txt"
	case "text/iuls":
		return "uls"
	case "application/x-vda":
		return "vda"
	case "application/x-vst":
		return "vst"
	case "application/vnd.visio":
		return "vsx"
	case "audio/x-ms-wax":
		return "wax"
	case "application/x-wb2":
		return "wb2"
	case "image/vnd.wap.wbmp":
		return "wbmp"
	case "application/x-wk3":
		return "wk3"
	case "application/x-wkq":
		return "wkq"
	case "video/x-ms-wm":
		return "wm"
	case "application/x-ms-wmd":
		return "wmd"
	case "text/vnd.wap.wml":
		return "wml"
	case "video/x-ms-wmx":
		return "wmx"
	case "application/x-wp6":
		return "wp6"
	case "application/x-wpg":
		return "wpg"
	case "application/x-wq1":
		return "wq1"
	case "application/x-wri":
		return "wri"
	case "text/scriptlet":
		return "wsc"
	case "video/x-ms-wvx":
		return "wvx"
	case "application/vnd.adobe.xfdf":
		return "xfdf"
	case "application/vnd.ms-excel":
		return "xls"
	case "application/x-xlw":
		return "xlw"
	case "application/x-x_b":
		return "x_b"
	case "application/vnd.symbian.install":
		return "sisx"
	case "application/vnd.iphone":
		return "ipa"
	case "application/x-silverlight-app":
		return "xap"
	default:
		return ""
	}
}
